language: python
matrix:
  include:
  - name: "Python 3.5, windows"
    os: windows 
    language: shell       # 'language: python' is an error on Travis CI Windows
    before_install:
      - choco install python --version 3.5.4
      - python -m pip install --upgrade pip
    env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    
  - name: "Python 3.6, linux"
    python: 3.6
    
  
install:
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt
  - pip install -e .
  
script:
  - python tasks.py --task=task_test 

after_success:
  - coveralls