language: python
python:
  - "3.6"
  - "3.7"
  
install:
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt
  - pip install -e .
  
script:
  - python tasks.py --task=task_test 

after_success:
  - coveralls