language: python
matrix:
  include:
  - name: "Python 3.6, Linux"
    python: 3.6
    before_install:
      - pip install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
    
  - name: "Python 3.6, Windows"
    os: windows 
    language: shell       # 'language: python' is an error on Travis CI Windows
    before_install:
      - choco install python --version 3.6.7
      - python -m pip install --upgrade pip
      - pip install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    
  - name: "Python 3.6 on macOS"
    os: osx
    osx_image: xcode9.4
    language: shell
    before_install:
      - pip3 install torch torchvision
    env: PATH=/Users/travis/Library/Python/3.6/bin:$PATH
    
  
install:
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt
  - pip install .
  
script:
  - python3 tasks.py --task=task_test || python tasks.py --task=task_test 

after_success:
  - coveralls