language: python
matrix:
  include:
  - name: "Python 3.6, windows"
    os: windows 
    language: shell       # 'language: python' is an error on Travis CI Windows
    python: 3.6
    
  - name: "Python 3.6, linux"
    dist: xenial 
    language: shell       # 'language: python' is an error on Travis CI Windows
    python: 3.6
    
  
install:
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt
  - pip install -e .
  
script:
  - python tasks.py --task=task_test 

after_success:
  - coveralls